server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://82.156.87.36:3306/mywebsite?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Playlol31415926!
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
